version: '3.8'

services:
  web:
    build: ..
    command: sh -c "
             python SupportAPI/manage.py migrate &&
             python SupportAPI/manage.py loaddata db_init.json &&
             python SupportAPI/manage.py createsuperuser --noinput --username admin --email a@gmail.com &&
             python SupportAPI/manage.py runserver 0.0.0.0:8000 "
    ports:
      - "8000:8000"
    env_file:
      - SupportAPI/.env
    restart: always
    depends_on:
      - db
      - redis
  db:
    image: postgres
    build: ..
#    volumes:
#      - ./data/db:/var/lib/postgresql/data
    ports:
      - "5431:5432"
    env_file:
      - db.env
      - SupportAPI/.env
    volumes:
      - database_data:/var/lib/postgresql/data
#      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
  redis:
    image: redis
    ports:
      - "6370:6379"
    hostname: redis
  celery:
    build: ..
    links:
      - redis

    command: bash -c " cd SupportAPI/ && celery -A SupportAPI worker -l info"
    volumes:
      - ./project/:/usr/src/app/
    env_file:
      - celery.env

    depends_on:
      - redis
volumes:
  project:
  database_data: