# Generated by Django 4.0.4 on 2022-05-24 20:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Support', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TicketMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=500, verbose_name='description')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Support.ticket', verbose_name='ticket')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
        ),
        migrations.AlterField(
            model_name='statusforticket',
            name='name',
            field=models.CharField(choices=[('open', 'open'), ('in process', 'in process'), ('closed', 'closed')], max_length=30, verbose_name='name'),
        ),
        migrations.DeleteModel(
            name='Message',
        ),
    ]
