# Generated by Django 4.0.4 on 2022-06-01 13:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Support', '0002_ticketmessage_alter_statusforticket_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Support.statusforticket', verbose_name='status'),
        ),
    ]
